sudo: false
language: node_js
node_js: "5.3"
addons:
  firefox: "46.0"
cache:
  directories:
      - node_modules
install: travis_retry npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - wct --local=firefox
